- name : user
  hosts : user
  become : yes
  tasks : 
  - name : disable old nodejs and enable nodejs
    ansible.builtin.shell : dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name : install nodejs
    ansible.builtin.dnf : 
      name : nodejs
      state : present

  - name : create roboshop user   
    ansible.builtin.user :
      name : roboshop

  - name: Recursively remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name : create app directory
    ansible.builtin.file : 
      path : /app
      state : directory

  - name : downloading the application
    ansible.builtin.get_url :
      url : https://roboshop-builds.s3.amazonaws.com/user.zip
      dest : /tmp

  - name : unzipping the applcation
    ansible.builtin.unarchive :
      src : /tmp/user.zip
      dest : /app
      remote_src: yes

  - name: Install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name : copy user service
    ansible.builtin.copy :
      src : user.service
      dest : /etc/systemd/system/user.service

  - name : daemon load the service and start
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name : copy mongodb repo
    ansible.builtin.copy :
      src : mongodb.repo
      dest : /etc/yum.repos.d/mongodb.repo

  - name : install mongodb
    ansible.builtin.package :
      name : mongodb-org-shell
      state : present
  
  - name : get the users count
    ansible.builtin.command :  mongo --host mongodb.allmydevops.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register : user_count  

  # - name : print the count
  #   ansible.builtin.debug :
  #     msg : "user count : {{user_count}}"

  - name : load the user
    ansible.builtin.command : mongo --host mongodb.allmydevops.online < /app/schema/user.js
    when : user_count.stdout == "0" # keep double quotes here for without skipping

  - name : start and enable user
    ansible.builtin.service :
      name : user
      state : restarted
      enabled : yes

  

